# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-18 22:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0002_auto_20180919_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='employer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', related_query_name='employee', to='CRM.Company'),
        ),
    ]
