# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-18 23:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0003_auto_20180919_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='employer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='CRM.Company'),
        ),
        migrations.AlterField(
            model_name='master',
            name='skill',
            field=models.ManyToManyField(related_name='skills', to='CRM.Skill'),
        ),
    ]
