# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-19 15:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0003_auto_20180919_1706'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='skills',
            new_name='service',
        ),
    ]
