# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-18 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0004_auto_20180919_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='skill',
            field=models.ManyToManyField(to='CRM.Skill'),
        ),
    ]
