# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-18 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0007_auto_20180919_0234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='master',
        ),
        migrations.AddField(
            model_name='master',
            name='skill',
            field=models.ManyToManyField(to='CRM.Skill'),
        ),
    ]
