# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-19 00:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0008_auto_20180919_0246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='master',
            name='skill',
        ),
        migrations.AddField(
            model_name='master',
            name='skill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='masters', to='CRM.Skill'),
        ),
    ]
