# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-19 00:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0009_auto_20180919_0306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='master',
            name='skill',
        ),
        migrations.AddField(
            model_name='master',
            name='skill',
            field=models.ManyToManyField(null=True, related_name='masters', to='CRM.Skill'),
        ),
    ]
