# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-23 02:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Tiki', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='name',
            new_name='task',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='body',
        ),
        migrations.AddField(
            model_name='ticket',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
