# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-23 02:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tiki', '0002_auto_20171223_0527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='date',
            field=models.DateField(),
        ),
    ]
