# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-03 20:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tiki', '0003_auto_20171223_0534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
